# Generated by Django 4.2 on 2026-01-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astronaut_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('medication_type', models.CharField(choices=[('ANALGESIC', 'Pain Relief'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTINAUSEA', 'Anti-Nausea'), ('SLEEP_AID', 'Sleep Aid'), ('ALLERGY', 'Allergy'), ('STIMULANT', 'Stimulant'), ('OTHER', 'Other')], max_length=20)),
                ('dosage', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('current_quantity', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=10)),
                ('container_location', models.CharField(max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('pill_image', models.ImageField(blank=True, null=True, upload_to='pill_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTH_SUCCESS', 'Authentication Success'), ('AUTH_FAILURE', 'Authentication Failure'), ('CONTAINER_UNLOCK', 'Container Unlocked'), ('PILL_RECOGNITION', 'Pill Recognition Attempt'), ('SYSTEM_ERROR', 'System Error')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('astronaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_inventory.astronaut')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_inventory.astronaut')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_inventory.medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_prescription', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='medical_inventory.astronaut')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_inventory.medication')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CHECKOUT', 'Medication Checkout'), ('RESTOCK', 'Inventory Restock'), ('EXPIRED', 'Expired Medication Removed'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medical_inventory.medication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_inventory.astronaut')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
