# Generated by Django 4.2 on 2026-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low Stock'), ('CRITICAL', 'Critical'), ('OUT', 'Out of Stock')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='container_location',
            field=models.CharField(default='A1', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('ANALGESIC', 'Pain Relief'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTINAUSEA', 'Anti-Nausea'), ('SLEEP_AID', 'Sleep Aid'), ('ALLERGY', 'Allergy'), ('STIMULANT', 'Stimulant'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
